---
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
tag-prefix: "v"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

categories:
  - title: '🔥 Breaking Changes'
    labels:
      - 'breaking'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '👋 Deprecated'
    labels:
      - 'deprecation'
  - title: '⛓  Dependency Updates'
    labels:
      - 'library-update'
      - 'dependencies'
  - title: '🛠  Internal Updates'
    labels:
      - 'internal'
      - 'kaizen'
      - 'test-library-update'
      - 'sbt-plugin-update'
  - title: '📚 Docs'
    labels:
      - 'documentation'

autolabeler:
  - label: "documentation"
    files:
      - "README.md"
      - "docs/**"
      - ".github/instructions/**"
  - label: "dependencies"
    files:
      - "pom.xml"
      - "**/pom.xml"
      - ".github/dependabot.yaml"
  - label: "ci"
    files:
      - ".github/workflows/**"
      - ".github/scripts/**"
  - label: "test"
    files:
      - "**/src/test/**"
      - "integration-tests/**"
  - label: "feature"
    branch:
      - "/feature\\/.+/"
    title:
      - "/^feat/i"
      - "/^feature/i"
  - label: "bug"
    branch:
      - "/fix\\/.+/"
    title:
      - "/^fix/i"
      - "/^bug/i"
  - label: "chore"
    branch:
      - "/chore\\/.+/"
    title:
      - "/^chore/i"

template: |
  ## What's Changed
  $CHANGES
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

